name: Notify Website Repo

on:
  push:
    branches:
      - main

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Emit Repository Dispatch
        run: |
          curl -X POST https://api.github.com/repos/YOUR_USERNAME/YOUR_WEBSITE_REPO_NAME/dispatches \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.GHP_TOKEN }}" \
          -d '{"event_type": "content-updated"}'
